### PR TITLE
Fixes #61: Feat: Make child's root comment collapseable

### LINKED ISSUE #61: Feature request: Toggle child comment's root
Hi @plibither8 

Quick thank you for your work, I've found this extension to be a great help navigating HN comments.

I've made a few CSS changes which fix some issues I had (see screenshot below):

- easier to collapse top-level comment
- easier to see at which indent level is the comment I'm reading

image

There is one feature I miss from a previous userscript: the ability to collapse all comments until the root of the tree of the current comment. For illustration purpose:

- Comment 1
- Comment 1.1
- Comment 1.2
- Comment 2
- Comment 2.1
- Comment 2.1.1

If I click on this new 'collapse parents' on comment 1.2, it would collapse all Comments 1, 1.1, 1.2. Ditto for 2.1.1 and 2, 2.1
I hope this is clear :)

In my vision, this feature would either be a button at the right of HN's default collapse button, or the top n pixels of the clickable side rail you've added yourself.

image

I figure I could hack something and submit a PR but I'm not quite sure I have the capacities to incorporate into your system. I suppose I'd have to getTopLevelComments() and find somehow the one that is the current comment's grand-parent, and then toggle that comment through its toggle button

Anyway, if you can show me some pointers I might be able to push something. Otherwise I'm available if you have questions :)

### PR DESCRIPTION
**Pull request by jvzr**
Adds a [collapse root] button on child comments, which collapses that comment's root.

Closes #61

### CODE REVIEW

**Comment by plibither8** [comment]
Hi! Excellent PR :+1: 

I've given it a test and it looks all okay to me. Before merging to master, I'd like you to run the linter to see that the code conforms to the predefined code-style. Run it like this: `npm run lint` to see the errors and `npm run lint-fix` to automatically fix most of them. Some of the errors you might have to manually fix.

**Comment by jvzr** [comment]
Will do tonight!

**Comment by jvzr** [comment]
Hey @plibither8 
I've run lint and lint-fix but I'm afraid I messed something up. It corrected a lot of files' line ending from LF to CRLF, hence creating a lot of changes.
Regarding the actual code, there are minor stylistic differences in collapse-root-comment.js, a var unused (metadata in init()) and a non-camelCase variable. I've fixed that, but I'm afraid to commit so many changes
What's going on? I'm sorry to come with such a problem

**Comment by jvzr** [comment]
I'm stupid. It should be OK now. Can you confirm? @plibither8

**Comment by plibither8** [comment]
Whoops, somehow my reply to your previous query did not get submitted properly, apologies!

Just checked your commit, great stuff! Also I really like the "auto-scroll", nice touch.

Thanks for your work on this feature, cheers!

**Comment by plibither8** [comment]
Just FYI, I've uploaded the updates to Mozilla and Chrome Web Store. Should update in some time. Congratulations! :smile:

**Comment by jvzr** [comment]
You're very kind, @plibither8! Thank you for guiding me through my first ever OS submission 😉

**Comment by plibither8** [comment]
It was my pleasure, loved to help! Do ping me any time you have any other issues :)

Have a good day!

**Comment by Wakeupbuddy** [comment]
just want to say thanks for this PR 👍

**Pull request merged**
